{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "chronicle-demo.pvcName" . }}
  labels:
    {{- include "chronicle-demo.labels" . | nindent 4 }}
  {{- with .Values.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if include "chronicle-demo.storageClass" . }}
  storageClassName: {{ include "chronicle-demo.storageClass" . }}
  {{- end }}
{{- end }}