{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "chronicle-demo.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chronicle-demo.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "chronicle-demo.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chronicle-demo.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "chronicle-demo.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "chronicle-demo.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}