{{- if .Values.openshift.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "chronicle-demo.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chronicle-demo.labels" . | nindent 4 }}
  {{- with .Values.openshift.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.openshift.route.host }}
  host: {{ .Values.openshift.route.host }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "chronicle-demo.fullname" . }}
    weight: 100
  port:
    targetPort: http
  {{- if .Values.openshift.route.tls.enabled }}
  tls:
    termination: {{ .Values.openshift.route.tls.termination }}
    {{- if .Values.openshift.route.tls.insecureEdgeTerminationPolicy }}
    insecureEdgeTerminationPolicy: {{ .Values.openshift.route.tls.insecureEdgeTerminationPolicy }}
    {{- end }}
    {{- if .Values.openshift.route.tls.certificate }}
    certificate: |
      {{- .Values.openshift.route.tls.certificate | nindent 6 }}
    {{- end }}
    {{- if .Values.openshift.route.tls.key }}
    key: |
      {{- .Values.openshift.route.tls.key | nindent 6 }}
    {{- end }}
    {{- if .Values.openshift.route.tls.caCertificate }}
    caCertificate: |
      {{- .Values.openshift.route.tls.caCertificate | nindent 6 }}
    {{- end }}
    {{- if .Values.openshift.route.tls.destinationCACertificate }}
    destinationCACertificate: |
      {{- .Values.openshift.route.tls.destinationCACertificate | nindent 6 }}
    {{- end }}
  {{- end }}
  wildcardPolicy: None
{{- end }}